name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, sqlite, bcmath, dom, fileinfo

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Validate Composer JSON
      run: composer validate

    - name: Diagnose Composer
      run: composer diagnose

    - name: Install Dependencies
      run: composer update --no-interaction --prefer-dist --no-progress

    - name: Generate key
      run: php artisan key:generate

    - name: Set directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create SQLite database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
